//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeLocation
    {
        public int ID { get; set; }
        public Nullable<int> TipeRumah { get; set; }
        public string AlamatRumah { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    }
}
